# Generated by Django 5.2.6 on 2025-09-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='location',
            field=models.CharField(default='Lokasi tidak diketahui', max_length=255),
        ),
        migrations.AddField(
            model_name='tweet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=140),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
