# Generated by Django 5.2.6 on 2025-09-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_tweet_latitude_alter_tweet_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=16, null=True),
        ),
    ]
